version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "iamaul/evonix-api:latest"
    container_name: evonix-api
    restart: unless-stopped
    env_file: .env
    networks:
      - default
    ports:
      - "5000:5000"
    
  nginx:
    build:
      context: ./nginx-conf
      dockerfile: Dockerfile
    image: "iamaul/nginx:latest"
    container_name: nginx
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8000:80"
    depends_on:
      - api

networks:
  default:
    external:
      name: gateway
