version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: evonix-ucp-backend-api
    env_file: .env
    environment:
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_HOST=mariadb
      - MYSQL_PORT="${MYSQL_PORT}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/iamaul/evonix-ucp-backend-api
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
    restart: unless-stopped

networks:
  backend:
    driver: bridge
