version: "3.7"

networks:
  evonix:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "evonixdev/evonix-ucp-backend-api:latest"
    container_name: evonix-api
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "5000:5000"
    networks:
      - evonix
