version: '3'
networks:
  mariadb:
    driver: bridge

services:
  database:
    container_name: database
    image: mariadb:10.4
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3307:3306"
    networks:
      - mariadb
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    image: evonix-ucp-backend-api
    env_file: .env
    environment:
      - MYSQL_USER="${DB_USER}"
      - MYSQL_PASSWORD="${DB_PASSWORD}"
      - MYSQL_HOST=database
      - MYSQL_PORT="${DB_PORT}"
      - MYSQL_DATABASE="${DB_NAME}"
    networks:
      - default
      - mariadb
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    volumes:
      - ./:/home/iamaul/evonix-ucp-backend-api
    restart: unless-stopped
